apiVersion: v1
kind: Service
metadata:
  name: {{ include "lightning-catalog.fullname" . }}
  labels:
    {{- include "lightning-catalog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.guiPort }}
      targetPort: gui
      protocol: TCP
      name: gui
  selector:
    {{- include "lightning-catalog.selectorLabels" . | nindent 4 }}
